### ISSUE TITLE
[BUG] Z position not saving

### ISSUE THREAD

**Issue by bartlomiejfornalczyk** [davidramiro/Marlin-Ai3M-2.0.x#10]
### Bug Description

Hi. I'm unable to set Z position in LCD menu, but also positioning instruction provided in the readme file doesn't work. I have sent those commands, saved, rebooted and Z axis is in the same position as it was - pressing the bed. 

### My Configurations

Anycubic I3 Mega with Chinese nozzle, which is 2.8mm higher than original.

### Steps to Reproduce

a) Change position of Z axis via LCD, save, reboot
b) Send  G91, G1, G90, or even M206, M428

**Actual behavior:** EEPROM is not being overwritten (?)

**Comment by davidramiro** [comment]
Z position does not get saved in EEPROM, maybe you mean Z offset? This cannot be set via LCD, only via GCode.

If you mean MMBL, those saved settings only get used when printing a GCode that has the Mesh enabled (with `M420 S1`).
