### ISSUE TITLE
[FR] Mega X Support

### ISSUE THREAD

**Issue by DunklerPhoenix** [davidramiro/Marlin-Ai3M-2.0.x#12]
Heho.

Will you support the Anycubic Mega-X?
What do you need for informations?

Here I posted the M503: https://www.reddit.com/r/anycubic/comments/fcqz6f/anycubic_megax_configurations_m503/

and here you get the firmwares:
https://www.reddit.com/r/anycubic/comments/fcsy92/anycubic_megax_stock_firmware/

The printer is nearly the same as Mega-S except of the size of X Y and Z and the acceleration rates.

Greetings

**Comment by davidramiro** [comment]
Probably not a big deal porting it, but it's hard for me without owning the device. From a first glance, the screen firmware changed. Hopefully they didn't change they way it communicates.

I am sure somebody who owns a Mega X can fork this firmware and get it to run.

**Comment by DunklerPhoenix** [comment]
Yeah the screen is a problem. I flashed a Mega-S Firmware for testing and the display didn't change a bit. Unfortunately I dont have enough programming experience to create a new interface ^^

**Comment by davidramiro** [comment]
The display interface doesn't change, it's hardcoded. It's just the communication between the screen and the board that this custom Marlin version handles. Maybe you can try and see if some of the functions of the new screen still work with this firmware?

**Comment by leberschnitzel** [comment]
I've flashed with this one.
Customized "configuration.h" it to bed size on line 888 + 889 + 897
Commented 559 to 566 to "stock drivers" (if someone knows what drivers are used, I'm happy to change.
Needed to reverse, so also changed lines 857-865 according to reverse comments.

Testing on screen: 
Heating bed works.
Heating Nozzle works.
Motor off works.
Home X works.
Home Y does seem to move the bed back instead.
Home Z works.
Move Axis: Z Works, Y /X don't.
Special Menu works.

My guess is I just need the right drivers for X / Y and then I can try again.

EDIT: Tests over Octoprint:
Moving X works
Moving Y works
Moving Z works
"Home X/y" homes X, but on the y it just moves the bed back further.

**Comment by leberschnitzel** [comment]
I tried a bit more but sadly no success so far.
Does someone have an idea in what direction I could test to get the Y axis working correctly?
I think now it might have to do with the new endstop, which is light based.

**Comment by Kit613** [comment]
leberschnitzel  mail me  kit613@o2.pl

**Comment by Kit613** [comment]
https://www.thingiverse.com/thing:4358011?fbclid=IwAR1VRPXaUGK98Lnl9ldNtQuv77tKaBSBPdUHT9QsI9JdIjhIh1ahsjY_6As

**Comment by jonatanpolak** [comment]
> https://www.thingiverse.com/thing:4358011?fbclid=IwAR1VRPXaUGK98Lnl9ldNtQuv77tKaBSBPdUHT9QsI9JdIjhIh1ahsjY_6As

Yes, this works. However, this is Marlin 1.1.9 version. And there was so many changes in version 2.0 that I would like to see in my printer :)

I have one question:
Printer Anycubic i3 Mega X 2020 - official firmware, https://github.com/ANYCUBIC-3D/MEGA_X_V1.2.6/blob/master/Configuration.h#L139
MOTHERBOARD BOARD_RAMPS_14_EFB

There has been a change and it is no longer BOARD_TRIGORILLA_14 in mega X, right?

**Comment by davidramiro** [comment]
Sorry, I can't really help you out there, I do not own a Mega-X. Since @Kit613 already made a port for it, I suggest you get in touch with him directly.

I do think it uses a Trigorilla board though. It's based on RAMPS 1.4, might be why it's called like that in their repo.
