### ISSUE TITLE
[BUG] Nozzle as Probe

### ISSUE THREAD

**Issue by Nissal1983** [davidramiro/Marlin-Ai3M-2.0.x#19]
Complier Error by Probe methode „nozzle as Probe or fix mounted Probe“ only with the Anycubic i3 Mega Stock Display. 
Complier Error:
Anycubic_TFT.cpp zprobe_zoffset was not declared in this scope

**Comment by davidramiro** [comment]
Did you change some BLtouch settings or similar before trying to compile?

**Comment by Nissal1983** [comment]
Ich glaube ich kann deutsch schreiben oder?? 
Nein, ich habe soweit noch keine Settings geändert. Ich habe manuel levling deaktievert, Mesh levling deaktiviert und Auto bed levling biliniar aktiviert. Als Probe nozzle as Probe aktiviert. Dann kommt der Fehler. Wenn ich einen bl Touch aktiviere kann ich kompilieren, auch geht es wenn ich das Orginal Display deaktivierte und nur ein reprap Display aktiviere. Er bringt den Fehler nur bei nozzle as Probe oder fix mounted Probe wenn das Anycubic Display aktiviert ist. Sonst hab ich keine Änderung gemacht.

**Comment by davidramiro** [comment]
Hab den Fehler gefunden. Gefixt in commit d47dbd5e4818d82c0353f178c58276aac77873b8.

**Comment by akula3** [comment]
Hallo David,

bei mir ist #define BLTOUCH aktiviert, da ich einen BLTouch Sensor für AUTO_BED_LEVELING_BILINEAR benutze.
Wird sich die Änderung in commit d47dbd5 für meinen Fall negativ auswirken?

**Comment by davidramiro** [comment]
Nein, kein Problem. Der Code dort war eigentlich schon lange überflüssig.
