### ISSUE TITLE
[BUG] Out of filament sensor does not trigger printing pause

### ISSUE THREAD

**Issue by gmag11** [davidramiro/Marlin-Ai3M-2.0.x#20]
### Bug Description

Filament sensor does not pause print. When filament is out of sensor a message is shown on screen but printing goes on normally.

### My Configurations

I'm running latest 2.0.x commit [d47dbd5e4818d82c0353f178c58276aac77873b8]

[Marlin.zip](https://github.com/davidramiro/Marlin-Ai3M-2.0.x/files/4476757/Marlin.zip)

### Steps to Reproduce

1. Put a piece of filament on sensor to simulate run out.
2. Start printing as usual
3. Remove filament from sensor

**Expected behavior:** I would expect that printing pauses waiting for new filament

**Actual behavior:** A message is shown on LCD, so sensor works fine. Printing process goes on.

**Comment by davidramiro** [comment]
This should be caused by the issue described here: https://github.com/davidramiro/Marlin-Ai3M-2.0.x/issues/5

Sorry, I haven't had the time recently to take a deeper look at this. I am quite busy with work these days, so I'll still have to postpone thoroughly testing this for a couple of weeks.

**Comment by davidramiro** [comment]
Just to confirm, you are printing from SD card, right?

**Comment by gmag11** [comment]
No, I am printing from Octoprint. Is that the reason maybe?

**Comment by davidramiro** [comment]
Yup, that is indeed the reason, the printer has no way of letting OctoPrint know that filament has run out, natively. You could install a filament sensor plugin and connect the filament sensor directly to the Pi, that would work well.

**Comment by gmag11** [comment]
I get this in OctoPrint's terminal:
```
Recv: TFT Serial Debug: Filament runout... J15
[...]
Recv: TFT Serial Debug: Filament runout recovered
[...]
Recv: DEBUG: Set filament trigger time
[...]
Recv: DEBUG: 3000ms delay done
Recv: TFT Serial Debug: Filament runout... J15
```
Could this be used to tell it to pause printer and park noozle?

**Comment by davidramiro** [comment]
You could write a plugin that detects this and stops the print, just not natively.
