### ISSUE TITLE
[BUG] Hot end fan runs only at 100%

### ISSUE THREAD

**Issue by gmag11** [davidramiro/Marlin-Ai3M-2.0.x#22]
### Bug Description
Does hot end fan support PWM control? It only blows when fan speed is set to 100%. In any other value fan keeps stopped.

### My Configurations

[Marlin.zip](https://github.com/davidramiro/Marlin-Ai3M-2.0.x/files/4548705/Marlin.zip)

### Steps to Reproduce

1. Use slicer to configure fan to be active at different speeds
2. Send gcode to print

**Expected behavior:** Fan should adapt its speed to setting

**Actual behavior:** Fan works only if speed is set to 100%

#### Additional Information

Fan I use is a 5015 like this: https://es.aliexpress.com/item/4000011565156.html

I'll try to connect an oscilloscope to check if PWM is applied. What setting should I ensure to be activated so that Fan 0 is controlled with PWM?

**Comment by davidramiro** [comment]
It's right there in the FAQ... 

https://github.com/davidramiro/Marlin-AI3M/wiki/Frequently-Asked-Questions#my-sunon-or-other-custom-fan-only-runs-at-100

https://github.com/davidramiro/Marlin-AI3M/wiki/Customization-&-Compiling#PWM-Settings

**Comment by gmag11** [comment]
Thank you. PWM signal is OK. Using stock blower works fine. I will read docs regarding PWM tunning
