### ISSUE TITLE
Mesh Bed Leveling won't go below endstops

### ISSUE THREAD

**Issue by nuberlang** [davidramiro/Marlin-Ai3M-2.0.x#25]
### Bug Description

When performing manual bed leveling, if a point on the bed is below the end-stops, the z-axis does not exceed that point so it cannot be leveled giving false level readings.

**Comment by davidramiro** [comment]
That is rather a safety measure than a bug. Elevate the whole platform by a few millimeters if you have multiple points that are below the endstops.
