### ISSUE TITLE
bug in operator overloading in Marlin/src/core/types.h

### ISSUE THREAD

**Issue by AndiP1234** [davidramiro/Marlin-Ai3M-2.0.x#27]
see at **https://github.com/MarlinFirmware/Marlin/pull/17826**

**Description**
In the file Marlin/src/core/types.h the operator overloading of operator* and operator/ for struct XYZval had a bug. See for example:

350: FI XYZval<T> operator* (const float &v) const { XYZval<T> ls = *this; ls.x *= v; ls.y *= v; ls.z *= z; return ls; }

here the value of z is not multiplied by v but by z instead.

**Benefits**
correct operations are ensured

**Comment by davidramiro** [comment]
Pulled the fix from upstream. Thanks for reporting this!
