### ISSUE TITLE
LV8729 Stepper driver

### ISSUE THREAD

**Issue by shaddow501** [davidramiro/Marlin-Ai3M-2.0.x#3]
Dear David

Maybe you can give some information.

I recently ordered the LV8729 motor  driver since I have heard good review about them.

I have installed them on the Z, Z2 & E0.
adjusted their voltage to about 1.100V.

Also made the modifications in the code:

#define Z_DRIVER_TYPE  LV8729 
#define Z2_DRIVER_TYPE LV8729 
#define E0_DRIVER_TYPE LV8729 

Also needed to switch the direction on the Z, and E0.
#define INVERT_Z_DIR true
#define INVERT_E0_DIR false

The direction now works fine the problem is that the moments is very slow and I also thing it is not the full movement.

My speculation that since it is by default 1/128 and not 1/16 could maybe cause this issue, but what I dont understand is why since if you define the driver type to be LV8729 it should know that that the stepping is 1/128 and work accordingly
![CgAGTFl8LauAKo8xAAVdUtF9gCA957](https://user-images.githubusercontent.com/21113491/70835703-8d734400-1e06-11ea-9535-16033b9563c6.jpg)

do you have any clue?
By the way it is not only on the 2.0 firmware it is also shown in the 1.19 firmware

Do I need to modify this as well??
 X, Y, Z, E0 [, E1[, E2[, E3[, E4]]]]

#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 412 } 
to:
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 3200, 3296} 

for Z (since the LV8729 is by default 1/128 according to the default of the main board)
1/16 = 400
1/32 = 800
1/64 = 1600
1/128 = 3200

For E0:
1/16 = 412
1/32 = 824
1/64 = 1648
1/128 = 3296

Is that correct?

What about the speed? they move very slow, will this change also accelerate the speed?

**Comment by davidramiro** [comment]
You will probably have to calibrate your steps. I have no experience with those kind of drivers so I can't really guide you through it but it seems probable that the higher microsteps need adjusted calibration of the axis steps per unit setting.

**Comment by shaddow501** [comment]
Well I am not sure that it will solve the speed problem...
I think that the best thing to do is to use those drivers as 1/16 configuration and that deals with some hardware tweaking... 
Remove pins MS1 & MS2 that will not get high value from the board socket (and not burn the board) and solder them to the GND pin...

Well that is the idiot way lol, just wanted to see how 1/128 bit of a driver will bring me into better printing, but as today we get very nice printing also from 1/16 drivers configuration and that being said, I even not sure if this upgrade to 1/128 or some use 1/256 will be noticeable in the printed model.

**Comment by davidramiro** [comment]
I only have really limited knowledge about microstepping, but what I do know for sure is that 128 or even 256 microsteps would be much more taxing to the puny little 8bit MCU on our Trigorilla. I'm not sure if it's up for the task.

To quote this thread on [StackExchange](https://3dprinting.stackexchange.com/questions/7572/0-9-motors-for-delta-printers):
>Also remember that if you are using 8-bit electronics (you hint to an ATMega board), then even 1/32 micro-stepping burdens the processor to achieve reasonable travel speeds. With 8-bit electronics, it is usually suggested to use 1/16 stepping.

**Comment by shaddow501** [comment]
Then I guess I will take the LV8729 remove pins MS1 & MS2 that will not get high value from the board socket (and not burn the board) and solder them to the GND pin...
Then it will be 1/16. (cause now it is 1/128 by default)
