### ISSUE TITLE
[NO-BUG] Changing Marlin language does not change screen language

### ISSUE THREAD

**Issue by OkiGraphics** [davidramiro/Marlin-Ai3M-2.0.x#31]
### Bug Description

Hi, I compiled the .hex file on my own, setting Czech language (#define LCD_LANGUAGE cz). After flashing the firmware and following all the steps in "How to flash this?" section, including sending of M commands, my printer has still original English language. In menu language setting still only switches between English and Chinese. I assume flashing the firmware was successful (no beeps on startup) and "Firmware version V116" in info screen:
![LCD](https://user-images.githubusercontent.com/76773557/103345668-49df8c80-4a92-11eb-9a7c-be951a58e5b8.jpg)

### My Configurations
Anycubic Mega-S
[Configuration.zip](https://github.com/davidramiro/Marlin-Ai3M-2.0.x/files/5753872/Configuration.zip)

### Steps to Reproduce

1. Download and configure Marlin-Ai3M-2.0.x
2. Compile and flash the firmware
3. M502; M500; M92 E384; M500
4. Restart printer

**Expected behavior:** 
Czech screen language

**Actual behavior:** [What actually happens]
English screen language

**Comment by davidramiro** [comment]
This is no bug. The screen does not use the language from Marlin, but has its own firmware with only English/Chinese as language.
