### ISSUE TITLE
Print menu crash

### ISSUE THREAD

**Issue by jyri87v** [davidramiro/Marlin-Ai3M-2.0.x#34]
I installed the hex ok and everything worked when i made the mesh. I put 7 files on the sd and when i put the sd in, i can see 3 of the first gcode files. If i move the menu down the firmware freezes.
Whats up with that.

**Comment by davidramiro** [comment]
Sorry for the super late answer, this is because there are special characters in the filename. I'm sure you've figured this out by now, so closing this issue. If you need more assistance, feel free to get back to me.
