### ISSUE TITLE
Hotend fan only 8V

### ISSUE THREAD

**Issue by vandykew** [davidramiro/Marlin-Ai3M-2.0.x#9]
According to the readme this firmware should put 12V to the hot end cooling fan, However I'm only seeing 8V on the fan output. Is this normal?

**Comment by davidramiro** [comment]
Are you measuring with a multimeter? It's a PWM signal, you won't get a reliable reading. You can check it with an oscilloscope, there you can make sure it's 12V.

**Comment by vandykew** [comment]
After swapping the board it reads 12V now
